### PR TITLE
Code update and general edits in import.js

### PR DESCRIPTION
**Pull request by EduSe7en42**
Updated some lists from "tweet", in the singular, to "tweets", in the plural. In addition to the addition of asynchronicity in the request function (axios).

### CODE REVIEW

**Comment by nukeador** [comment]
@EduSe7en42 is your fork in working state? Since I can't create issues here I have to comment that the current code in this repo is not working for me:

```
evalmachine.<anonymous>:1
window.YTD.tweets.part0 = [
                        ^

TypeError: Cannot set property 'part0' of undefined
    at evalmachine.<anonymous>:1:25
    at Script.runInContext (vm.js:143:18)
    at getTweets (/home/user/bin/import-tweets-to-mastodon/import.js:44:10)
    at Object.<anonymous> (/home/uservalmachine.<anonymous>:1
window.YTD.tweets.part0 = [
                        ^

TypeError: Cannot set property 'part0' of undefined
    at evalmachine.<anonymous>:1:25
    at Script.runInContext (vm.js:143:18)
    at getTweets (/home/user/bin/import-tweets-to-mastodon/import.js:44:10)
    at Object.<anonymous> (/home/user/bin/import-tweets-to-mastodon/import.js:124:14)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:72:12)
    at internal/main/run_main_module.js:17:47e/bin/import-tweets-to-mastodon/import.js:124:14)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:72:12)
    at internal/main/run_main_module.js:17:47
```

**Comment by EduSe7en42** [comment]
@nukeador I switched to draft. Can you edit now?

**Comment by nukeador** [comment]
I was not looking to edit, just realizing this repository doesn't have issues enabled, that's why I added my comment in there :sweat_smile:

**Review by EduSe7en42 — COMMENTED** [review]
Code changes for better performance

**Comment by FGRibreau** [comment]
Hello @EduSe7en42, thank you, I've merged another PR, please open again a PR if you wish to add something else :)

**Pull request closed without merging**
